language: ruby
rvm:
- 2.3.0
script:
- bundle install
- bundle exec rake db:create db:schema:load
- bundle exec rspec/models/
- bundle exec rspec/controllers/
- bundle exec rspec/presenters/
deploy:
  provider: heroku
  api_key:
    secure: DBbotOt8/y4DbvdCgsj7bJsYYXw4Qq/WkiGTpzUIVIABLZ44F49YJYxVN6a6Q2PfyFZRe3UAA/dzxH1l1eo5KN9ObsMMVE6N/8s1kApiyq17zh2vaq0V5I0E2ohbJeIeYmWtQB6RcLNbOJLaWDSSnE+1p2WUqBntTs/tQ2H4vdWgu41V8SF7r8kWsDhLrjp9SdSLBhTYf0tGcaaZ2/QBwEhPcUr810KHVRRGAalIu2v3N7RnmdU4zYoEQAwcDVl92bu9t7SBZ6hBxGxOkxODlSWnHNOEqeMcii412m+wU7/lPxX8YNxOguTBbRhyxL36fhNV06qhoRxRRkwlqhDqMi0QSUoW0B/KE5F+LB36E2Ie2/1R6k26JY4XEZoUix3Vh5zrOec7X3k5SRvLOGi8wy4bs3+FS76VrP5zB6ptdejqUuueJLEwWKkM9rHX5ZeuP5e6eh7nWW/yww2YzR2+ZzN0mPV33u3BQyYmK/UHZ8LEdjk9I/U7wHoWjP8O0xcYeJcwZA2tyrsngD7Ib7MjxgwhZf7vGrrS5PFvHVasmcSnqeWR3pzU5QA1Nr+RyDlsHuvZuOUQFA51wOxtxP6XB2WX4YHvjixYSRB681t6W+6+zGK1HuIz8/wfG/CdZKWD7zYhc2facZqC5LXKac1f633BxoQ7DphNfFm6O0G4v7g=
  app: creditsmarts
  on:
    repo: bad6e/credit_cards
    branch: master
